var GAME_LEVELS = [
  ["                       y         y y y y y y y y      y                         ",
   "                   y      y  y  y y y y y y y y y  y     y         y            ",
   "                       y       y y y y yyyyy y y y    y      y                  ",
   "              y           y  y  y y yoyyyoyyyoy y y      y                      ",
   "                       y       y y yyyyyyyyyyyyy y y oy         y               ",
   "                   y      y  y  yxxxxxxzzzzzxxxxxxy      y                      ",
   "         y             y       xxxxxxx!zzzzz!xxxxxxx  y      y      y           ",
   "                           y  xxxxxxxx!zzozz!xxxxxxxx    y                      ",
   "                     y    o  xxxxxxxxx!zzzzz!xxxxxxxxx   o                      ",
   "                        y   xxxxxxxxxx!zzzzz!xxxxxxxxxx y      y                ",
   "               y           xxxxxxxxxxx!zzozz!xxxxxxxxxxx                        ",
   "                          xxxxzzzzxxxx!zzzzz!xxxxxxxxxxxx                       ",
   "                         xxxzzzzzz!xxx!zzzzz!xxxxxxxxxxxxx    o                 ",
   "                     o  xxxxzzzozz!xxx!zzozz!xxxxxxxxxxxxxx                     ",
   "                       xxxxxzzzzzz!xxx!zzzzz!xxxxxxxxxxxxxxxx       o      o    ",
   "                     xxxxxxxzzzzzzxxxx!zzzzz!xxxxxxxxxxxxxxxxxxx                ",
   "                   xxxxxxzzzzzozzzzxxx!!zoz!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                 xxxxx!!xzzxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx",
   "          o    xxxxx!!!!xzzzzzzzzzzzzzzzzzzzzozzzzozzzzozzzzozzzzzzzzzzozzzzozzx",
   "             xxxxx!!!!!!xzzzzxxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx",
   "          xxxxxx!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx",
   "   @   xxxxxx!!!!!!!!!!!xxxxxxxxxxxxx!!xxxxx!!xxx^ xxx^ xxx^ xxx^ xxxxxxxxzzozzx",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx",
   "xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzz@zzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzozzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzozzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzxxxxxxxxxzzzzzxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxx!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzozzx!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzvzzzx!!!!!!!!!!!!!!!!!!!!xzzozzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!xxxzzzzzzzzozzzzzzzzzozzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzozzzzzzzx!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzozzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!zzzzzx!!!!!!!!!!!!!!!!!!!!xzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!zzzzzoxxxxxxxxxxxxxxxxxxxxxxzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!zzzzzxxzzzzzzzzzzzzzzzzzzzzzzzzozzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!zozzzzzzzzzzozzzzzozzzzzzzzzzzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzozzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!zxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzozzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzz%$zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzz%$zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzo%$zzzzzzzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzz%$zzzzzzzzzzzzzzzzzzzzzzzozzzzzzzzozzzzzozzzzzzzzozzzzzzzozzzzzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!x!!!xxxxxxxxxxxxxxxxxxxxxxxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxzz^zzzzzzz^zzzzzzz^zzzzzzzzozzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzozzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!xx!!!!!xxx!!!!!xxxzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxzzozzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzx!!!!!",
   "!!!!xxxxxxxx!xxxxxxx!xxxxxx!xxxxxx!xxxxxx!xxxxxxxxx!!!xxxx!!!xxxx!!!xxxx!!!xxxx!!!xxxxxxxxxxxxxxozzzzzzzx!!!!!",
   "!!!!xzzzzzzzvzzzzzzzvzzzzzzvzzzzzzvzzzzzzvzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%$zzzzzzzzx!!!!!",
   "!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzozzzzzzozzzzzzozzzzzzozzzzzzzzzzzzzzzzzzzz%$zzzzzzzzx!!!!!",
   "!!!!xzzzzzzzozzzzzzzozzzzzzozzzzzzozzzzzzozzzzzzzzzz^zzzzzz^zzzzzz^zzzzzz^zzzzzz^zzzzzzzzzozzz%$zzzzzozxx!!!!!",
   "!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%$zzzzzzzzx!!!!!",
   "!!!!xzzozzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xx!!!!!xx!!!!!xx!!!!!xx!!!!!xxxxxxxxxxxxxxxxxxxxxx!!!!!",
   "!!!!xzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!xzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!xzz@zzx!!!!!!!!!!!!!!!!!!!!!xxxxx!!xxxxxxxxxxxxxxxxxxxxx!!xxxxx!!xxxxxxxx!!xxxxx!!xxxxxxxxxxxx!!!!!!!!!!!!",
   "!!!!xzzzzzx!!!!!!!!!!!!!!!!!xxxxxzzzzvvzzzzzzzzzzzzzzzzzzzzzvvzzzzzvvzzzzzzzzvvzzzzzvvzzzzzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzzzzx!!!!!!!!!!!!!!xxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzzzzx!!!!!!!!!!!!xxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzozzx!!!!!!!!!!!xxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzozzzzzzzzzozzzzzzx!!!!!!!!!!!!",
   "!!!!xzzzzzx!!!!!!!!!!xxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzzzzx!!!!!!!!!xxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxxxxxxxxxxxxxxxxxxzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzzzzxxxxxxxxxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxxzzzzzzzx!!!!!!!!!!!!!!!!xzzzzzzzx!!!!!!!!!!!!",
   "!!!!xzzozzzzzzzzz%$zzzzzzzzzozzzzzzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!xxxzzzzzxxxxxxxx!!!!!",
   "!!!!xzzzzzzzzozzz%$zzzzzozzzzzzzzzzzzzzzzzzzzzoozzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!xzzzozzzzzzzzzzx!!!!!",
   "!!!!xzzzzzzzzzzzz%$zzzzzzzzzzzzzzzzzzxxzzzzzzzzzzzzzzzzxxzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!xzzzzzzzzzzzozzx!!!!!",
   "!!!!xxxxxxxxxxxxxxxxxxxxxzzzzzzzzzzzzzzzzzz^zzzzzz^zzzzzzzzzzzzzzzzzozzzx!!!!!!!!!!!!!!!!xzzzxxzzzzzzzzzx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzxxx!!!!!!!!!!!!xxxzzzzzzzzxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzxx!!!!!!!!!!!!xxzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzxx!!!!!!!!!!xxzzzzzzxxxzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzxxx!!!!!!xxxzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzxxxxxxxxzzzzzozzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxxxxzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzxxxzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzxxxzzzzzzzzzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzxxzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzxxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxxxxxxxxx!!xxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzozzzzzzzzzzzzzzzzzzzzzzzozzzzzzzzzzzozzzzzzz$%zzzzzzzvvzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz$%zzzzzzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxzzzzxxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzoozzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzxxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzoozzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzxxxxxxxxxxxxxxxxxxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzzzzx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzozzzzzzzzozzzzzzzzzzzx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xzzzzzzzzzzzzzzzzzzzzzzzzozzx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxzzzzzx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!"],
  ["xxxxzzzzzx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxx z@z x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxz z zx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxx     x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxx z z x!!!!!!!!!!!!!!!!!!!!xxxx                                                                            ",
   "xxxx     x!!!!!!!!!!!!!!!!!!xxx                                                                               ",
   "xxxx  z  x!!!!!!!!!!!!!!!!xxx             y   y                                                               ",
   "xxxx     x!!!!!!!!!!!!!!xxx                                                                                   ",
   "xxxx     xxxxxxxxxxxxxxxx                   y    y                                                            ",
   "xxxx     %$                                   y                                                               ",
   "xxxx  o  %$  o                          y     y                                                               ",
   "xxxx     %$                                  y    y               x                                           ",
   "xxxxxxxxxxxxxxx    o                          y                   x                                           ",
   "xxxxxxxxxxxxxxxxx                        y    yy                 xx                                           ",
   "xxxxxxxxxxxxxxxxxxxxx    o                    yy        xxxxx  xxx                                            ",
   "!!!!xxxxxxxxxxxxxxxxxxx                        xx    xxxxx!!xxxxx                                     xxx     ",
   "!!!!!!xxxxxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxx                                      xx    ",
   "!!!!!!!!!!!!!!!!!xxxxxxxxxx                    xzzzzzzzzzzzzzzzzzxxx                                     xx   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                        zzzzzzzzzzzzzzzxxx                                     xx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                          zzzzzzzzzzozzzxxx                                     x  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                      zzzzzz!!!!!xxzzzzzzzxxxxxxxxxxxxxxxxxxxxxxxxx            xxx ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                    xxxxxxxxxxxxxxxxxzzzzzzzzzzzxxxxxxxxxxxxxxxxxxxxxxx       xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                               xxxxxxxzzzzozzzzzzzzzzzzzzzzxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                                   xxxxxzzzzzzzzzzozzzzzzzzoozzxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                                     xxxxzzzzzzzzzzzzzzzzzzoozzzz!!!!!!xxx!xxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                                     xxxxxxxzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!xxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                                     xxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!^        ^                           xxxxxx!xxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                                     xxxxxxx!x!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!   ^  ^      ^               ^   xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!                  ^     ^        xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                              ",
   "                                                             o",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "     x   x  xxxxx x   x      x       x  xxxxx  x   x  x       ",
   "     x   x  x   x x   x      x       x    x    xx  x  x       ",
   "      x x   x   x x   x      x       x    x    x x x  x       ",
   "       x    x   x x   x       x  x  x     x    x x x  x       ",
   "       x    x   x x   x       x x x x     x    x  xx          ",
   "       x    xxxxx xxxxx        x   x    xxxxx  x   x  x       ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "   @                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
